version: "3.3"
services:
  mongodb:
    image : mongo:4.4.6
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - kbox-network
  kbox:
    image: ${kbox/manager}:${v1}
    restart: unless-stopped
    networks:
      - kbox-network
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    environment:
      MONGO_LOCATION: "mongodb"
      MONGO_PORT: "27017"
networks:
  kbox-network:
